import Head from 'next/head'
import Contenedor from '../components/Contenedor'
import Footer from '../components/footer'
import Header from '../components/Header'
import Quotes from '../components/Quotes'

export default function Home() {


  return (
    <div>
      <Head>
        <title>BTS Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/> 
     <Contenedor/>
     <Footer/>


    </div>
  )
}
